"""empty message

Revision ID: 3ff498adb1d2
Revises: b50f24557bd9
Create Date: 2023-05-14 15:41:00.509636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ff498adb1d2'
down_revision = 'b50f24557bd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('banner_pic', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('banner_pic')
        batch_op.drop_column('country')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
